'use client';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './contexts/AuthContext';
import { SessionProvider } from './contexts/SessionContext';
import { LiveKitProvider } from './contexts/LiveKitContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50`}>
        {typeof window === undefined ? (
          <div />
        ) : (
          <AuthProvider>
            <SessionProvider>
              <LiveKitProvider>
                <main className="container mx-auto p-4 sm:p-6 lg:p-8 max-w-screen-xl">{children}</main>
              </LiveKitProvider>
            </SessionProvider>
          </AuthProvider>
        )}
      </body>
    </html>
  );
}
