import { z } from 'zod';
export const UserSchema = z.object({
    id: z.string().cuid(),
    email: z.string().email(),
    passwordHash: z.string(),
    roles: z.array(z.enum(['USER', 'BROADCASTER', 'ADMIN'])),
    isActive: z.boolean(),
    emailVerified: z.boolean(),
    lastLoginAt: z.date().optional(),
    loginAttempts: z.number().int(),
    lockedUntil: z.date().optional(),
    createdAt: z.date(),
    updatedAt: z.date(),
});
export const SessionSchema = z.object({
    id: z.string().cuid(),
    type: z.enum(['P2P', 'BROADCAST']),
    accessType: z.enum(['PUBLIC', 'PRIVATE']),
    passwordHash: z.string().optional(),
    title: z.string().max(100),
    description: z.string().max(500).optional(),
    status: z.enum(['INITIALIZING', 'ACTIVE', 'PAUSED', 'ENDED']),
    maxParticipants: z.number().int(),
    currentParticipants: z.number().int(),
    hostId: z.string().cuid(),
    settings: z.any().optional(),
    liveKitRoomId: z.string().optional(),
    startedAt: z.date().optional(),
    endedAt: z.date().optional(),
    createdAt: z.date(),
    updatedAt: z.date(),
});
export const ParticipantSchema = z.object({
    id: z.string().cuid(),
    sessionId: z.string().cuid(),
    userId: z.string().cuid().optional(),
    participantIdentity: z.string(),
    displayName: z.string().max(50),
    role: z.enum(['HOST', 'GUEST', 'BROADCASTER', 'VIEWER']),
    status: z.enum(['CONNECTING', 'CONNECTED', 'DISCONNECTED', 'KICKED']),
    permissions: z.array(z.string()),
    joinedAt: z.date(),
    leftAt: z.date().optional(),
    lastActivityAt: z.date(),
    isAudioEnabled: z.boolean(),
    isVideoEnabled: z.boolean(),
    isScreenShareEnabled: z.boolean(),
    connectionQuality: z.enum(['EXCELLENT', 'GOOD', 'POOR']).optional(),
    deviceInfo: z.any().optional(),
    ipAddress: z.string().optional(),
});
export const RefreshTokenSchema = z.object({
    id: z.string().cuid(),
    userId: z.string().cuid(),
    tokenHash: z.string(),
    deviceInfo: z.any().optional(),
    ipAddress: z.string().optional(),
    isActive: z.boolean(),
    expiresAt: z.date(),
    lastUsedAt: z.date().optional(),
    createdAt: z.date(),
});
